version: '3'

services:
  db:
    image: mishadhd/todo_db
    environment:
      POSTGRES_DB: "docker_app_db"
      POSTGRES_USER: "docker_app"
      POSTGRES_PASSWORD: "docker_app"

    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready","-U","docker_app"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    image: mishadhd/todo_backend
    environment:
      HOST: db
      PORT: 5432
      DB: docker_app_db
      DB_USERNAME: docker_app
      DB_PASSWORD: docker_app

    healthcheck:
      test: ["CMD","curl","fail", "localhost:8000/test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
        db:
          condition: service_healthy
  nginx:
    image: mishadhd/todo_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  todo_db:


