- name: deploy frontend
  hosts: hosts
  tasks:
    - name: send config file
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: ./nginx.conf



    - name: Install python docker
      apt: name=python3-docker state=latest
    

    - name: create network
      docker_network:
        name: todo_net

    - name: Deploy postgres
      docker_container:
        name: postgres
        image: mishadhd/todo_db
        state: started
        networks:
          - name: todo_net
        env:
          POSTGRES_DB: docker_app_db
          POSTGRES_USER: docker_app
          POSTGRES_PASSWORD: docker_app


    - name: deploy backend
      docker_container:
        name: backend
        image: mishadhd/todo_backend
        state: started
        networks:
          - name: todo_net
        env:
          HOST: postgres
          PORT: "5432"
          DB: docker_app_db
          DB_USERNAME: docker_app
          DB_PASSWORD: docker_app




    - name: Deploy container nginx
      docker_container:
        name: nginx
        image: mishadhd/todo_nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro 
        networks:
          - name: todo_net
        ports:
          - 80:80
  
